version: '3.9'
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 4000:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
  mongo-db:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=artists
    volumes:
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"   
    depends_on:
      - backend
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"   
    depends_on:
      - mongo-db



